class Session {
  final String id;
  final String creatorId;
  final String title;
  final String description;
  final DateTime date;
  final String startTime;
  final String endTime;
  final String location;
  final bool isOnline;
  final String platform;
  final String color;
  final List<String> invitees;
  final bool notificationSet; 

  Session({
    required this.id,
    required this.creatorId,
    required this.title,
    required this.description,
    required this.date,
    required this.startTime,
    required this.endTime,
    required this.location,
    required this.isOnline,
    required this.platform,
    required this.color,
    required this.invitees,
    required this.notificationSet, 
  });
}



List<Session> dummySessions = [
  Session(
    id: "s1",
    creatorId: "u1",
    title: "Sales Role Interview",
    description: "A sales interview with a potential client. The meeting is set to take place on Zoom, a zone.",
    date: DateTime(2024, 7, 2),
    startTime: "11:30 AM",
    endTime: "12:30 PM",
    location: "Remote, Zoom",
    isOnline: true,
    platform: "Zoom",
    color: "#00E676",
    invitees: ["u2", "u3"],
    notificationSet: true,
  ),
  Session(
    id: "s2",
    creatorId: "u2",
    title: "Software Eng Mentorship",
    description: "A discussion on how to create scalable software products with your mentor development strategy.",
    date: DateTime(2024, 7, 3),
    startTime: "3:00 PM",
    endTime: "4:30 PM",
    location: "Accra, Ghana",
    isOnline: false,
    platform: "",
    color: "#6200EA",
    invitees: ["u1", "u3"],
    notificationSet: false,
  ),
  Session(
    id: "s3",
    creatorId: "u3",
    title: "Team Collaboration",
    description: "A behavioral interview with the Aya data group of companies for the frontend engineering role.",
    date: DateTime(2024, 7, 4),
    startTime: "8:30 PM",
    endTime: "9:30 PM",
    location: "Remote, Google Meet",
    isOnline: true,
    platform: "Google Meet",
    color: "#FF1744",
    invitees: ["u1", "u2"],
    notificationSet: true,
  ),
  Session(
    id: "s4",
    creatorId: "u1",
    title: "Client Pitch",
    description: "Pitching our new product to potential clients.",
    date: DateTime(2024, 7, 5),
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    location: "New York, USA",
    isOnline: false,
    platform: "",
    color: "#FBC02D",
    invitees: ["u2", "u3"],
    notificationSet: true,
  ),
  Session(
    id: "s5",
    creatorId: "u2",
    title: "Product Demo",
    description: "Demoing the latest features of our software.",
    date: DateTime(2024, 7, 6),
    startTime: "2:00 PM",
    endTime: "3:00 PM",
    location: "San Francisco, USA",
    isOnline: false,
    platform: "",
    color: "#03A9F4",
    invitees: ["u1"],
    notificationSet: false,
  ),
  Session(
    id: "s6",
    creatorId: "u3",
    title: "Team Building Exercise",
    description: "Building team spirit and collaboration.",
    date: DateTime(2024, 7, 7),
    startTime: "4:00 PM",
    endTime: "6:00 PM",
    location: "Accra, Ghana",
    isOnline: false,
    platform: "",
    color: "#4CAF50",
    invitees: ["u1", "u2"],
    notificationSet: true,
  ),
  Session(
    id: "s7",
    creatorId: "u1",
    title: "Project Planning",
    description: "Planning the next quarter's projects.",
    date: DateTime(2024, 7, 8),
    startTime: "9:00 AM",
    endTime: "10:30 AM",
    location: "Remote",
    isOnline: true,
    platform: "Zoom",
    color: "#9C27B0",
    invitees: ["u2", "u3"],
    notificationSet: false,
  ),
  Session(
    id: "s8",
    creatorId: "u2",
    title: "Marketing Strategy Meeting",
    description: "Discussing the marketing strategy for the upcoming product launch.",
    date: DateTime(2024, 7, 9),
    startTime: "1:00 PM",
    endTime: "2:30 PM",
    location: "London, UK",
    isOnline: false,
    platform: "",
    color: "#FF9800",
    invitees: ["u1", "u3"],
    notificationSet: true,
  ),
  Session(
    id: "s9",
    creatorId: "u3",
    title: "User Interface Design Review",
    description: "Reviewing and refining the UI design for our mobile app.",
    date: DateTime(2024, 7, 10),
    startTime: "11:00 AM",
    endTime: "12:30 PM",
    location: "Remote",
    isOnline: true,
    platform: "Google Meet",
    color: "#4CAF50",
    invitees: ["u1", "u2"],
    notificationSet: true,
  ),
  Session(
    id: "s10",
    creatorId: "u1",
    title: "Product Roadmap Discussion",
    description: "Mapping out the product roadmap for the next year.",
    date: DateTime(2024, 7, 2),
    startTime: "3:00 PM",
    endTime: "4:30 PM",
    location: "Remote",
    isOnline: true,
    platform: "Zoom",
    color: "#00BCD4",
    invitees: ["u2", "u3"],
    notificationSet: false,
  ),
  Session(
    id: "s11",
    creatorId: "u2",
    title: "Code Review Session",
    description: "Conducting a code review for the latest feature branch.",
    date: DateTime(2024, 7, 3),
    startTime: "9:00 AM",
    endTime: "10:00 AM",
    location: "Accra, Ghana",
    isOnline: false,
    platform: "",
    color: "#FF5722",
    invitees: ["u1"],
    notificationSet: true,
  ),
  Session(
    id: "s12",
    creatorId: "u3",
    title: "Client Feedback Meeting",
    description: "Gathering feedback from our clients on the latest product update.",
    date: DateTime(2024, 7, 4),
    startTime: "11:00 AM",
    endTime: "12:00 PM",
    location: "Remote, Google Meet",
    isOnline: true,
    platform: "Google Meet",
    color: "#9C27B0",
    invitees: ["u1", "u2"],
    notificationSet: false,
  ),
  Session(
    id: "s13",
    creatorId: "u1",
    title: "Sales Strategy Brainstorming",
    description: "Brainstorming session to devise new sales strategies.",
    date: DateTime(2024, 7, 5),
    startTime: "4:00 PM",
    endTime: "5:30 PM",
    location: "New York, USA",
    isOnline: false,
    platform: "",
    color: "#FFEB3B",
    invitees: ["u2", "u3"],
    notificationSet: true,
  ),
  Session(
    id: "s14",
    creatorId: "u2",
    title: "Product Launch Preparation",
    description: "Preparing for the upcoming product launch event.",
    date: DateTime(2024, 7, 6),
    startTime: "10:00 AM",
    endTime: "11:30 AM",
    location: "San Francisco, USA",
    isOnline: false,
    platform: "",
    color: "#FF9800",
    invitees: ["u1"],
    notificationSet: false,
  ),
  Session(
    id: "s15",
    creatorId: "u3",
    title: "Team Training Session",
    description: "Training session for new team members on our development workflow.",
    date: DateTime(2024, 7, 7),
    startTime: "2:00 PM",
    endTime: "3:30 PM",
    location: "Accra, Ghana",
    isOnline: false,
    platform: "",
    color: "#4CAF50",
    invitees: ["u1", "u2"],
    notificationSet: true,
  ),
  Session(
    id: "s16",
    creatorId: "u1",
    title: "Client Onboarding Meeting",
    description: "Onboarding a new client to our services.",
    date: DateTime(2024, 7, 8),
    startTime: "3:30 PM",
    endTime: "4:30 PM",
    location: "Remote",
    isOnline: true,
    platform: "Zoom",
    color: "#2196F3",
    invitees: ["u2", "u3"],
    notificationSet: true,
  ),
 Session(
    id: "s17",
    creatorId: "u2",
    title: "Market Research Analysis",
    description: "Analyzing the results of our latest market research survey.",
    date: DateTime(2024, 7, 9),
    startTime: "11:00 AM",
    endTime: "12:00 PM",
    location: "London, UK",
    isOnline: false,
    platform: "",
    color: "#FFC107",
    invitees: ["u1", "u3"],
    notificationSet: false,
  ),
  Session(
    id: "s18",
    creatorId: "u3",
    title: "Content Strategy Meeting",
    description: "Discussing the content strategy for our blog and social media channels.",
    date: DateTime(2024, 7, 10),
    startTime: "2:00 PM",
    endTime: "3:30 PM",
    location: "Remote, Google Meet",
    isOnline: true,
    platform: "Google Meet",
    color: "#673AB7",
    invitees: ["u1", "u2"],
    notificationSet: true,
  ),
  Session(
    id: "s19",
    creatorId: "u1",
    title: "Finance Review",
    description: "Reviewing the quarterly financial performance.",
    date: DateTime(2024, 7, 10),
    startTime: "9:00 AM",
    endTime: "10:00 AM",
    location: "Remote",
    isOnline: true,
    platform: "Zoom",
    color: "#009688",
    invitees: ["u2", "u3"],
    notificationSet: true,
  ),
  Session(
    id: "s20",
    creatorId: "u2",
    title: "Team Retrospective",
    description: "Reflecting on the team's recent projects and identifying areas for improvement.",
    date: DateTime(2024, 7, 2),
    startTime: "4:30 PM",
    endTime: "6:00 PM",
    location: "Accra, Ghana",
    isOnline: false,
    platform: "",
    color: "#795548",
    invitees: ["u1", "u3"],
    notificationSet: true,
  ),
];