import 'dart:math';

import 'package:connecto/models/connection_model.dart';
import 'package:connecto/models/event_model.dart';
import 'package:connecto/models/job_feed_model.dart';
import 'package:connecto/models/user_model.dart';

// Function to get a random avatar URL
String getRandomAvatar() {
  List<String> avatars = [
    "https://randomuser.me/api/portraits/men/1.jpg",
    "https://randomuser.me/api/portraits/women/1.jpg",
    "https://randomuser.me/api/portraits/men/2.jpg",
    "https://randomuser.me/api/portraits/women/2.jpg",
    "https://randomuser.me/api/portraits/men/3.jpg",
    "https://randomuser.me/api/portraits/women/3.jpg",
  ];
  return avatars[Random().nextInt(avatars.length)];
}


// Dummy data for users
List<User> userDataList = [
  User(
    userId: '12345',
    name: 'Kwame Mensah',
    email: 'kwame.mensah@example.com',
    password: 'password123',
    profilePicture: getRandomAvatar(),
    bio: 'Software developer with a passion for mobile apps.',
    skills: {'programming': 'Dart, Flutter', 'design': 'UI/UX'},
    location: {'latitude': 5.6037, 'longitude': -0.1870},
    address: 'Accra, Ghana',
    role: 'mentor',
  ),
  User(
    userId: '67890',
    name: 'Ama Osei',
    email: 'ama.osei@example.com',
    password: 'password456',
    profilePicture: getRandomAvatar(),
    bio: 'Graphic designer with a love for digital art.',
    skills: {'design': 'Photoshop, Illustrator', 'animation': 'After Effects'},
    location: {'latitude': 6.5244, 'longitude': -0.2333},
    address: 'Kumasi, Ghana',
    role: 'mentee',
  ),
  User(
    userId: '11223',
    name: 'Kojo Asante',
    email: 'kojo.asante@example.com',
    password: 'password789',
    profilePicture: getRandomAvatar(),
    bio: 'Data scientist specializing in machine learning and AI.',
    skills: {'data_analysis': 'Python, R', 'machine_learning': 'TensorFlow, Keras'},
    location: {'latitude': 5.5560, 'longitude': -0.1969},
    address: 'Tema, Ghana',
    role: 'mentor',
  ),
  User(
    userId: '44556',
    name: 'Yaa Nyarko',
    email: 'yaa.nyarko@example.com',
    password: 'password101',
    profilePicture: getRandomAvatar(),
    bio: 'Marketing expert with a focus on social media strategy.',
    skills: {'marketing': 'SEO, Content Marketing', 'social_media': 'Facebook, Instagram'},
    location: {'latitude': 6.1300, 'longitude': -0.1962},
    address: 'Cape Coast, Ghana',
    role: 'mentee',
  ),
  User(
    userId: '77889',
    name: 'Kofi Boateng',
    email: 'kofi.boateng@example.com',
    password: 'password202',
    profilePicture: getRandomAvatar(),
    bio: 'Full-stack developer with expertise in web technologies.',
    skills: {'programming': 'JavaScript, React, Node.js', 'database': 'MongoDB, SQL'},
    location: {'latitude': 5.8267, 'longitude': -0.2931},
    address: 'Takoradi, Ghana',
    role: 'mentor',
  ),
  User(
    userId: '99112',
    name: 'Akua Appiah',
    email: 'akua.appiah@example.com',
    password: 'password303',
    profilePicture: getRandomAvatar(),
    bio: 'Digital marketer with a knack for content creation.',
    skills: {'marketing': 'Content Marketing, SEO', 'social_media': 'LinkedIn, Twitter'},
    location: {'latitude': 5.5608, 'longitude': -0.2057},
    address: 'Kasoa, Ghana',
    role: 'mentee',
  ),
];





List<Connection> connectionDataList = [
  Connection(
    connectionId: 'conn1',
    userId: '12345',
    connectedUserId: '67890',
    status: 'pending',
  ),
  Connection(
    connectionId: 'conn2',
    userId: '11223',
    connectedUserId: '44556',
    status: 'accepted',
  ),
  Connection(
    connectionId: 'conn3',
    userId: '77889',
    connectedUserId: '99112',
    status: 'pending',
  ),
  Connection(
    connectionId: 'conn4',
    userId: '44556',
    connectedUserId: '12345',
    status: 'rejected',
  ),
  Connection(
    connectionId: 'conn5',
    userId: '67890',
    connectedUserId: '11223',
    status: 'accepted',
  ),
  Connection(
    connectionId: 'conn6',
    userId: '12345',
    connectedUserId: '77889',
    status: 'accepted',
  ),
  Connection(
    connectionId: 'conn7',
    userId: '12345',
    connectedUserId: '44556',
    status: 'pending',
  ),
];



// Dummy data for events
List<Event> eventDataList = [
  Event(
    eventId: 'event1',
    creatorId: '12345',
    title: 'Tech Talk on Flutter',
    description: 'Join us for an interactive session on Flutter development.',
    startTime: DateTime(2024, 7, 10, 14, 0), // July 10, 2024, 2:00 PM
    endTime: DateTime(2024, 7, 10, 16, 0),   // July 10, 2024, 4:00 PM
    eventImage: 'https://example.com/event1.jpg',
    creator: User(
      userId: '12345',
      name: 'Kwame Mensah',
      email: 'kwame.mensah@example.com',
      password: 'password123',
      profilePicture: 'https://randomuser.me/api/portraits/men/1.jpg',
      bio: 'Software developer with a passion for mobile apps.',
      skills: {'programming': 'Dart, Flutter', 'design': 'UI/UX'},
      location: {'latitude': 5.6037, 'longitude': -0.1870},
      role: 'mentor',
      address: 'Accra, Ghana',
    ),
  ),
  Event(
    eventId: 'event2',
    creatorId: '11223',
    title: 'Webinar on Machine Learning',
    description: 'Learn about the latest trends in machine learning.',
    startTime: DateTime(2024, 7, 15, 10, 0), // July 15, 2024, 10:00 AM
    endTime: DateTime(2024, 7, 15, 12, 0),   // July 15, 2024, 12:00 PM
    eventImage: 'https://example.com/event2.jpg',
    creator: User(
      userId: '11223',
      name: 'Kojo Asante',
      email: 'kojo.asante@example.com',
      password: 'password789',
      profilePicture: 'https://randomuser.me/api/portraits/men/2.jpg',
      bio: 'Data scientist specializing in machine learning and AI.',
      skills: {'data_analysis': 'Python, R', 'machine_learning': 'TensorFlow, Keras'},
      location: {'latitude': 5.5560, 'longitude': -0.1969},
      role: 'mentor',
      address: 'Tema, Ghana',
    ),
  ),
  Event(
    eventId: 'event3',
    creatorId: '77889',
    title: 'Networking Mixer',
    description: 'Connect with professionals in your industry.',
    startTime: DateTime(2024, 7, 20, 18, 0), // July 20, 2024, 6:00 PM
    endTime: DateTime(2024, 7, 20, 20, 0),   // July 20, 2024, 8:00 PM
    eventImage: 'https://example.com/event3.jpg',
    creator: User(
      userId: '77889',
      name: 'Kofi Boateng',
      email: 'kofi.boateng@example.com',
      password: 'password202',
      profilePicture: 'https://randomuser.me/api/portraits/men/3.jpg',
      bio: 'Full-stack developer with expertise in web technologies.',
      skills: {'programming': 'JavaScript, React, Node.js', 'database': 'MongoDB, SQL'},
      location: {'latitude': 5.8267, 'longitude': -0.2931},
      role: 'mentor',
      address: 'Takoradi, Ghana',
    ),
  ),
  Event(
    eventId: 'event4',
    creatorId: '44556',
    title: 'Startup Pitch Competition',
    description: 'Pitch your startup idea to potential investors.',
    startTime: DateTime(2024, 7, 25, 13, 0), // July 25, 2024, 1:00 PM
    endTime: DateTime(2024, 7, 25, 15, 0),   // July 25, 2024, 3:00 PM
    eventImage: 'https://example.com/event4.jpg',
    creator: User(
      userId: '44556',
      name: 'Yaa Nyarko',
      email: 'yaa.nyarko@example.com',
      password: 'password101',
      profilePicture: 'https://randomuser.me/api/portraits/women/1.jpg',
      bio: 'Marketing expert with a focus on social media strategy.',
      skills: {'marketing': 'SEO, Content Marketing', 'social_media': 'Facebook, Instagram'},
      location: {'latitude': 6.1300, 'longitude': -0.1962},
      role: 'mentee',
      address: 'Cape Coast, Ghana',
    ),
  ),
  Event(
    eventId: 'event5',
    creatorId: '67890',
    title: 'Panel Discussion on Digital Marketing',
    description: 'Insights from experts on the future of digital marketing.',
    startTime: DateTime(2024, 8, 1, 11, 0),  // August 1, 2024, 11:00 AM
    endTime: DateTime(2024, 8, 1, 13, 0),    // August 1, 2024, 1:00 PM
    eventImage: 'https://example.com/event5.jpg',
    creator: User(
      userId: '67890',
      name: 'Ama Osei',
      email: 'ama.osei@example.com',
      password: 'password456',
      profilePicture: 'https://randomuser.me/api/portraits/women/2.jpg',
      bio: 'Graphic designer with a love for digital art.',
      skills: {'design': 'Photoshop, Illustrator', 'animation': 'After Effects'},
      location: {'latitude': 6.5244, 'longitude': -0.2333},
      role: 'mentee',
      address: 'Kumasi, Ghana',
    ),
  ),
  Event(
    eventId: 'event6',
    creatorId: '12345',
    title: 'Workshop on Mobile App Design',
    description: 'Hands-on session on designing user-friendly mobile apps.',
    startTime: DateTime(2024, 8, 5, 15, 0),  // August 5, 2024, 3:00 PM
    endTime: DateTime(2024, 8, 5, 17, 0),    // August 5, 2024, 5:00 PM
    eventImage: 'https://example.com/event6.jpg',
    creator: User(
      userId: '12345',
      name: 'Kwame Mensah',
      email: 'kwame.mensah@example.com',
      password: 'password123',
      profilePicture: 'https://randomuser.me/api/portraits/men/1.jpg',
      bio: 'Software developer with a passion for mobile apps.',
      skills: {'programming': 'Dart, Flutter', 'design': 'UI/UX'},
      location: {'latitude': 5.6037, 'longitude': -0.1870},
      role: 'mentor',
      address: 'Accra, Ghana',
    ),
  ),
];



List<JobFeed> jobFeedDataList = [
  JobFeed(
    feedId: 'feed1',
    creatorId: 'google',
    type: 'Full-time',
    title: 'Software Engineer',
    description: 'Join our engineering team to work on innovative projects.',
    postedDate: DateTime(2024, 7, 10),
    salaryRange: 'USD 120,000 - 150,000',
    requirements: [
      'Proficiency in Python and Java',
      'Experience with cloud platforms',
      'Strong problem-solving skills',
      'Knowledge of software architecture principles',
      'Ability to work in an Agile environment',
    ],
    jobType: 'Engineering',
    companyDetails: 'Google Inc.',
    companyLogo: 'https://banner2.cleanpng.com/20180610/jeu/kisspng-google-logo-google-search-google-now-5b1dacc1ad0462.3234288415286714257087.jpg',
    backgroundPicture: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201707/google-campus-main-pic_559_070617104054.jpg',
    location: 'Mountain View, California, USA',
  ),
  JobFeed(
    feedId: 'feed2',
    creatorId: 'mtn',
    type: 'Internship',
    title: 'Marketing Intern',
    description: 'Gain hands-on experience in digital marketing strategies.',
    postedDate: DateTime(2024, 7, 15),
    salaryRange: 'Paid internship',
    requirements: [
      'Strong communication skills',
      'Knowledge of social media platforms',
      'Creative thinking ability',
      'Understanding of market research techniques',
      'Ability to analyze marketing data',
    ],
    jobType: 'Marketing',
    companyDetails: 'MTN Group',
    companyLogo: 'https://banner2.cleanpng.com/20180610/jeu/kisspng-google-logo-google-search-google-now-5b1dacc1ad0462.3234288415286714257087.jpg',
    backgroundPicture: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201707/google-campus-main-pic_559_070617104054.jpg',
    location: 'Johannesburg, South Africa',
  ),
  JobFeed(
    feedId: 'feed3',
    creatorId: 'tullow',
    type: 'Contract',
    title: 'Petroleum Engineer',
    description: 'Work on challenging projects in the oil and gas industry.',
    postedDate: DateTime(2024, 7, 20),
    salaryRange: 'Negotiable',
    requirements: [
      'Degree in Petroleum Engineering',
      'Experience in offshore drilling',
      'Knowledge of reservoir engineering',
      'Familiarity with environmental regulations',
      'Project management skills',
    ],
    jobType: 'Engineering',
    companyDetails: 'Tullow Oil',
    companyLogo:'https://s3.eu-west-1.amazonaws.com/assets.stepchangeinsafety.net/logos/tullowoil.png',
    backgroundPicture: 'https://www.tullowoil.com/application/files/cache/thumbnails/41bf28408fc546b3c6ed618f9c29beca.jpg',
    location: 'London, UK',
  ),
  JobFeed(
    feedId: 'feed4',
    creatorId: 'bankofghana',
    type: 'Full-time',
    title: 'Financial Analyst',
    description: 'Analytical role supporting monetary policy decisions.',
    postedDate: DateTime(2024, 7, 25),
    salaryRange: 'GHS 80,000 - 100,000',
    requirements: [
      'Strong analytical skills',
      'Experience in financial modeling',
      'Knowledge of economic indicators',
      'Ability to present financial data effectively',
      'Attention to detail',
    ],
    jobType: 'Finance',
    companyDetails: 'Bank of Ghana',
    companyLogo:'https://s3.us-east-1.amazonaws.com/cdn.designcrowd.com/blog/120-cool-logos-for-a-fresh-new-look/FAMOUS/Apple.png',
    backgroundPicture: 'https://miro.medium.com/v2/resize:fit:1200/1*4joN1zzSUgu03Yjt_8kcTg.png',
    location: 'Accra, Ghana',
  ),
  JobFeed(
    feedId: 'feed5',
    creatorId: 'google',
    type: 'Part-time',
    title: 'UX/UI Designer',
    description: 'Create intuitive and visually appealing user interfaces.',
    postedDate: DateTime(2024, 7, 30),
    salaryRange: 'USD 90,000 - 110,000',
    requirements: [
      'Proficiency in Adobe XD/Sketch',
      'Experience in mobile design',
      'Knowledge of usability principles',
      'Understanding of front-end development',
      'Ability to conduct user research',
    ],
    jobType: 'Design',
    companyDetails: 'Google Inc.',
    companyLogo: 'https://banner2.cleanpng.com/20180610/jeu/kisspng-google-logo-google-search-google-now-5b1dacc1ad0462.3234288415286714257087.jpg',
    backgroundPicture: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201707/google-campus-main-pic_559_070617104054.jpg',
    location: 'San Francisco, California, USA',
  ),
  JobFeed(
    feedId: 'feed6',
    creatorId: 'mtn',
    type: 'Full-time',
    title: 'Network Engineer',
    description: 'Maintain and optimize telecommunications networks.',
    postedDate: DateTime(2024, 8, 5),
    salaryRange: 'ZAR 600,000 - 800,000',
    requirements: [
      'Certification in Cisco CCNA/CCNP',
      'Experience in network troubleshooting',
      'Knowledge of network security principles',
      'Understanding of IP routing protocols',
      'Ability to deploy network infrastructure',
    ],
    jobType: 'Engineering',
    companyDetails: 'MTN Group',
    companyLogo: 'https://banner2.cleanpng.com/20180610/jeu/kisspng-google-logo-google-search-google-now-5b1dacc1ad0462.3234288415286714257087.jpg',
    backgroundPicture: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201707/google-campus-main-pic_559_070617104054.jpg',
    location: 'Cape Town, South Africa',
  ),
  JobFeed(
    feedId: 'feed7',
    creatorId: 'tullow',
    type: 'Contract',
    title: 'Environmental Scientist',
    description: 'Conduct environmental impact assessments and develop mitigation strategies.',
    postedDate: DateTime(2024, 8, 10),
    salaryRange: 'GBP 50,000 - 70,000',
    requirements: [
      'Degree in Environmental Science',
      'Knowledge of regulatory requirements',
      'Experience in environmental auditing',
      'Ability to write technical reports',
      'Fieldwork experience',
    ],
    jobType: 'Environmental',
    companyDetails: 'Tullow Oil',
    companyLogo:'https://s3.eu-west-1.amazonaws.com/assets.stepchangeinsafety.net/logos/tullowoil.png',
    backgroundPicture: 'https://www.tullowoil.com/application/files/cache/thumbnails/41bf28408fc546b3c6ed618f9c29beca.jpg',
    location: 'Accra, Ghana',
  ),
  JobFeed(
    feedId: 'feed8',
    creatorId: 'bankofghana',
    type: 'Internship',
    title: 'Research Analyst Intern',
    description: 'Assist in economic research and data analysis projects.',
    postedDate: DateTime(2024, 8, 15),
    salaryRange: 'GHS 3,000 - 4,000',
    requirements: [
      'Strong analytical skills',
      'Proficiency in statistical software',
      'Ability to interpret economic trends',
      'Experience with data visualization tools',
      'Excellent written and verbal communication skills',
    ],
    jobType: 'Research',
    companyDetails: 'Bank of Ghana',
    companyLogo:'https://s3.us-east-1.amazonaws.com/cdn.designcrowd.com/blog/120-cool-logos-for-a-fresh-new-look/FAMOUS/Apple.png',
    backgroundPicture: 'https://miro.medium.com/v2/resize:fit:1200/1*4joN1zzSUgu03Yjt_8kcTg.png',
    location: 'Accra, Ghana',
  ),

  JobFeed(
    feedId: 'feed9',
    creatorId: 'google',
    type: 'Full-time',
    title: 'Data Scientist',
    description: 'Utilize data to drive business insights and decision-making.',
    postedDate: DateTime(2024, 8, 20),
    salaryRange: 'USD 130,000 - 160,000',
    requirements: [
      'Proficiency in statistical analysis tools (e.g., R, Python)',
      'Experience with machine learning algorithms',
      'Strong mathematical and analytical skills',
      'Ability to communicate complex findings to non-technical stakeholders',
      'Experience in big data technologies (e.g., Hadoop, Spark)',
    ],
    jobType: 'Data Science',
    companyDetails: 'Google Inc.',
    companyLogo: 'https://banner2.cleanpng.com/20180610/jeu/kisspng-google-logo-google-search-google-now-5b1dacc1ad0462.3234288415286714257087.jpg',
    backgroundPicture: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201707/google-campus-main-pic_559_070617104054.jpg',
    location: 'Kumasi, Ghana',
  ),
  JobFeed(
    feedId: 'feed10',
    creatorId: 'mtn',
    type: 'Full-time',
    title: 'Customer Support Manager',
    description: 'Lead a team to deliver exceptional customer service.',
    postedDate: DateTime(2024, 8, 25),
    salaryRange: 'ZAR 400,000 - 600,000',
    requirements: [
      'Proven experience in customer support management',
      'Excellent interpersonal and leadership skills',
      'Ability to resolve complex customer issues',
      'Knowledge of CRM systems',
      'Fluency in multiple languages',
    ],
    jobType: 'Customer Support',
    companyDetails: 'MTN Group',
    companyLogo: 'https://banner2.cleanpng.com/20180610/jeu/kisspng-google-logo-google-search-google-now-5b1dacc1ad0462.3234288415286714257087.jpg',
    backgroundPicture: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201707/google-campus-main-pic_559_070617104054.jpg',
    location: 'Takoradi, Ghana',
  ),

  JobFeed(
    feedId: 'feed12',
    creatorId: 'google',
    type: 'Full-time',
    title: 'Product Manager',
    description: 'Lead product development initiatives and strategy.',
    postedDate: DateTime(2024, 9, 1),
    salaryRange: 'USD 140,000 - 170,000',
    requirements: [
      'Experience in product lifecycle management',
      'Strong leadership and communication skills',
      'Ability to prioritize and manage multiple projects',
      'Understanding of market trends and customer needs',
      'Experience in Agile development methodologies',
    ],
    jobType: 'Product Management',
    companyDetails: 'Google Inc.',
    companyLogo: 'https://banner2.cleanpng.com/20180610/jeu/kisspng-google-logo-google-search-google-now-5b1dacc1ad0462.3234288415286714257087.jpg',
    backgroundPicture: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201707/google-campus-main-pic_559_070617104054.jpg',
    location: 'Accra, Ghana',
  ),
  JobFeed(
    feedId: 'feed13',
    creatorId: 'mtn',
    type: 'Internship',
    title: 'Software Developer Intern',
    description: 'Gain practical experience in software development.',
    postedDate: DateTime(2024, 9, 5),
    salaryRange: 'Paid internship',
    requirements: [
      'Basic understanding of programming languages (e.g., Java, Python)',
      'Knowledge of web development frameworks (e.g., React, Angular)',
      'Ability to learn quickly and adapt to new technologies',
      'Strong problem-solving skills',
      'Good teamwork and communication skills',
    ],
    jobType: 'Software Development',
    companyDetails: 'MTN Group',
    companyLogo: 'https://banner2.cleanpng.com/20180610/jeu/kisspng-google-logo-google-search-google-now-5b1dacc1ad0462.3234288415286714257087.jpg',
    backgroundPicture: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201707/google-campus-main-pic_559_070617104054.jpg',
    location: 'Kumasi, Ghana',
  ),
  JobFeed(
    feedId: 'feed14',
    creatorId: 'tullow',
    type: 'Contract',
    title: 'Health and Safety Officer',
    description: 'Implement health and safety protocols on site.',
    postedDate: DateTime(2024, 9, 10),
    salaryRange: 'GBP 40,000 - 60,000',
    requirements: [
      'Certification in Occupational Health and Safety',
      'Experience in risk assessment and incident investigation',
      'Knowledge of health and safety legislation',
      'Strong attention to detail',
      'Effective communication skills',
    ],
    jobType: 'Health and Safety',
    companyDetails: 'Tullow Oil',
    companyLogo:'https://s3.eu-west-1.amazonaws.com/assets.stepchangeinsafety.net/logos/tullowoil.png',
    backgroundPicture: 'https://www.tullowoil.com/application/files/cache/thumbnails/41bf28408fc546b3c6ed618f9c29beca.jpg',
    location: 'Takoradi, Ghana',
  ),
  JobFeed(
    feedId: 'feed15',
    creatorId: 'bankofghana',
    type: 'Full-time',
    title: 'Risk Analyst',
    description: 'Assess financial risks and develop mitigation strategies.',
    postedDate: DateTime(2024, 9, 15),
    salaryRange: 'GHS 90,000 - 110,000',
    requirements: [
      'Experience in risk management or financial analysis',
      'Strong analytical and problem-solving skills',
      'Knowledge of banking regulations',
      'Ability to interpret complex financial data',
      'Attention to detail and accuracy',
    ],
    jobType: 'Finance',
    companyDetails: 'Bank of Ghana',
    companyLogo:'https://s3.us-east-1.amazonaws.com/cdn.designcrowd.com/blog/120-cool-logos-for-a-fresh-new-look/FAMOUS/Apple.png',
    backgroundPicture: 'https://miro.medium.com/v2/resize:fit:1200/1*4joN1zzSUgu03Yjt_8kcTg.png',
    location: 'Accra, Ghana',
  ),
  JobFeed(
    feedId: 'feed16',
    creatorId: 'google',
    type: 'Part-time',
    title: 'Content Writer',
    description: 'Create engaging content for various digital platforms.',
    postedDate: DateTime(2024, 9, 20),
    salaryRange: 'USD 60,000 - 80,000',
    requirements: [
      'Proven experience in content creation (e.g., articles, blogs)',
      'Excellent writing and editing skills',
      'Understanding of SEO principles',
      'Ability to work independently and meet deadlines',
      'Creativity and attention to detail',
    ],
    jobType: 'Content Creation',
    companyDetails: 'Google Inc.',
    companyLogo: 'https://banner2.cleanpng.com/20180610/jeu/kisspng-google-logo-google-search-google-now-5b1dacc1ad0462.3234288415286714257087.jpg',
    backgroundPicture: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201707/google-campus-main-pic_559_070617104054.jpg',
    location: 'Accra, Ghana',
  ),
];

